### ISSUE TITLE
Wrong version of monaco-editor is being downloaded from CDN

### ISSUE THREAD

**Issue by DrakeAnglin** [ngstack/code-editor#1295]
The library download the monaco-editor from the CDN but does not specify the version, therefor the library is downloading the latest. They released a new version of monaco-editor today and this library is downloading the new version which doesn't appear to be compatible with this library. 

Our app have crashed in production because of this issue. I do not see any documentation that shows how to specify the version of monaco-editor we want to use.

**Comment by DrakeAnglin** [comment]
I do see that there is a baseUrl options, however i think there is still a bug that the library is not setting its baseUrl to the version it requires.

**Comment by luke37b** [comment]
I solved this by installing monaco-editor@0.44 ( I picked this specific version because I read somewhere else it worked fine, but feel free to try with newer ones).

Then, setting this in the `angular.json`, inside the `build/assets` block:

`{
                "glob": "**/*",
                "input": "./node_modules/monaco-editor/min/",
                "output": "/assets/monaco-editor"
              }`

to import the files into the assets folder.

And finally, importing the module with this config in `app.module`

` CodeEditorModule.forRoot({
      baseUrl: 'assets/monaco-editor',
    }),`

It's working fine now.

**Comment by DrakeAnglin** [comment]
We did do the same, but it required a break fix in production because the library was using the latest. This will most likely be a issue for other people as well as future changes to the base monaco library. At the very least clarify the documentation so that users of the library are aware of the risk of not specifically setting this in there project.

I would however recommend adding the monaco version into the output string for the asset glob incase you have caching on your server or if you are using a service worker.

```json
{
  "input": "node_modules/monaco-editor/min",
  "output": "./assets/monaco@0.46.0",
  "glob": "**/*"
}
```
and then adding
```ts
CodeEditorModule.forRoot({
  baseUrl: 'assets/monaco@0.46.0',
}),
```

**Comment by DenysVuika** [comment]
There's a separate section in the README for the offline setup: https://github.com/ngstack/code-editor?tab=readme-ov-file#offline-setup

**Comment by DenysVuika** [comment]
@DrakeAnglin the latest 7.1.0 has support for `editorVersion` property (defaults to `latest`) that allows you customizing the monaco editor version if you want to use CDN instead of local hosting. See https://github.com/ngstack/code-editor/blob/v.7.1.0/README.md#integrating-with-angular-cli-project for more details.
